apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamatera-rke2-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kamatera-rke2-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kamatera-rke2-controller
    spec:
      serviceAccountName: kamatera-rke2-controller
      containers:
        - name: manager
          image: ghcr.io/kamatera/kamatera-rke2-controller:latest
          args:
            - "-not-ready-duration=15m"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 64Mi
